alter session set container = XEPDB1;
select * from SoftwareCategories ;
delete from SoftwareCategories where CategoryId > 5;
ALTER TABLE SoftwareCategories MODIFY CategoryName NVARCHAR2(100) NULL;

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(CategoryID),0) INTO v_max FROM SoftwareCategories;

    EXECUTE IMMEDIATE 'ALTER TABLE SoftwareCategories MODIFY CategoryID GENERATED BY DEFAULT AS IDENTITY START WITH ' || (v_max + 1);
END;
/




INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Windows', 1);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Linux', 1);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Microsoft Office 365', 2);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Adobe Creative Suite', 2);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Visual Studio', 5);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('IntelliJ Platform', 5);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('MySQL', 4);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Oracle DB', 4);


INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Windows 10', 6);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Windows 11', 6);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Photoshop', 7);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Illustrator', 7);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('IntelliJ IDEA', 8);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('PyCharm', 8);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Excel', 3);
INSERT INTO SoftwareCategories (CategoryName, ParentCategoryID) VALUES ('Word', 3);



SELECT * FROM SoftwareCategories;
BEGIN
    GetChildCategories(2);
END;
/

BEGIN
    AddChildCategory(18, 'Дитё_2 InteliJ IDEA');
END;
/

SELECT * FROM SoftwareCategories;
BEGIN
    GetChildCategories(2);
END;
/

BEGIN
    AddChildCategory(3, 'Блокнот IDE');
END;
/

SELECT * FROM SoftwareCategories;
BEGIN
    GetChildCategories(3);
END;
/

SELECT * FROM SoftwareCategories;
BEGIN
    GetChildCategories(3);
END;
/
BEGIN
    AddChildCategory(10, 'Поддерево');
END;
/

SELECT * FROM SoftwareCategories;
BEGIN
    GetChildCategories(2);
END;
/
BEGIN
    GetChildCategories(5);
END;
/
BEGIN
    MoveChildCategories(2, 24);
END;
/

SELECT * FROM SoftwareCategories;
BEGIN
    GetChildCategories(3);
END;
/

BEGIN
    GetChildCategories(24);
END;
/

BEGIN
    GetChildCategories(8);
END;
/

BEGIN
    MoveChildCategories(8, NULL);
END;
/

SELECT * FROM SoftwareCategories;

BEGIN
    GetChildCategories(18);
END;
/





















