ALTER SESSION SET CONTAINER = XEPDB1;
show con_name;

CREATE TABLE DeviceType (
    DeviceTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DeviceTypeName NVARCHAR2(50) UNIQUE
);

CREATE TABLE Rooms (
    RoomID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoomName NVARCHAR2(50) UNIQUE,
    DeviceTypeID NUMBER NOT NULL,
    CONSTRAINT FK_Rooms_DeviceType FOREIGN KEY (DeviceTypeID)
        REFERENCES DeviceType(DeviceTypeID)
);

CREATE TABLE Vendors (
    VendorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VendorName NVARCHAR2(150) NOT NULL UNIQUE,
    Email NVARCHAR2(150) UNIQUE,
    Password NVARCHAR2(255) NOT NULL
);

CREATE TABLE SoftwareCategories (
    CategoryID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryName NVARCHAR2(100) NOT NULL UNIQUE,
    ParentCategoryID NUMBER NULL,
    CONSTRAINT FK_SoftwareCategories_Parent FOREIGN KEY (ParentCategoryID)
        REFERENCES SoftwareCategories(CategoryID)
);

CREATE TABLE Software (
    SoftwareID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SoftwareName NVARCHAR2(150) NOT NULL,
    VendorID NUMBER NOT NULL,
    CategoryID NUMBER NOT NULL,
    CONSTRAINT FK_Software_Vendor FOREIGN KEY (VendorID)
        REFERENCES Vendors(VendorID),
    CONSTRAINT FK_Software_Category FOREIGN KEY (CategoryID)
        REFERENCES SoftwareCategories(CategoryID)
);

CREATE TABLE Licenses (
    LicenseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SoftwareID NUMBER NOT NULL,
    RoomID NUMBER NOT NULL,
    PurchaseDate DATE NOT NULL,
    ExpirationDate DATE NOT NULL,
    Price NUMBER(10,2) NOT NULL CHECK (Price >= 0),
    LicenseCount NUMBER NOT NULL CHECK (LicenseCount > 0),
    CONSTRAINT FK_Licenses_Software FOREIGN KEY (SoftwareID)
        REFERENCES Software(SoftwareID),
    CONSTRAINT FK_Licenses_Room FOREIGN KEY (RoomID)
        REFERENCES Rooms(RoomID),
    CONSTRAINT CHK_Licenses_Dates CHECK (ExpirationDate >= PurchaseDate)
);



CREATE OR REPLACE VIEW LicenseInfo AS
SELECT 
    l.LicenseID,
    s.SoftwareName,
    v.VendorName,
    r.RoomName,
    dt.DeviceTypeName,
    l.PurchaseDate,
    l.ExpirationDate,
    l.Price,
    l.LicenseCount
FROM Licenses l
JOIN Software s ON l.SoftwareID = s.SoftwareID
JOIN Vendors v ON s.VendorID = v.VendorID
JOIN Rooms r ON l.RoomID = r.RoomID
JOIN DeviceType dt ON r.DeviceTypeID = dt.DeviceTypeID;


CREATE OR REPLACE TRIGGER CheckLicenseDates
BEFORE INSERT OR UPDATE ON Licenses
FOR EACH ROW
BEGIN
    IF :NEW.ExpirationDate < :NEW.PurchaseDate THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Дата окончания лицензии не может быть меньше даты покупки'
        );
    END IF;
END;

CREATE INDEX LicensesSoftwareID ON Licenses(SoftwareID);






CREATE OR REPLACE FUNCTION EndingLicensesCount(p_days NUMBER)
RETURN NUMBER
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM Licenses WHERE ExpirationDate >= SYSDATE AND ExpirationDate <= SYSDATE + p_days;
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION LicenseCostByRoom(p_roomid NUMBER)
RETURN NUMBER
IS
    v_total NUMBER(12,2);
BEGIN
    SELECT NVL(SUM(Price * LicenseCount),0) INTO v_total FROM Licenses WHERE RoomID = p_roomid;
    RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION VendorSoftwareCount(p_vendorid NUMBER)
RETURN NUMBER
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM Software WHERE VendorID = p_vendorid;
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION VendorSoftwareCount(p_vendorid NUMBER)
RETURN NUMBER
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM Software WHERE VendorID = p_vendorid;
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION IsLicenseActive(p_licenseid NUMBER)
RETURN NUMBER
IS
    v_result NUMBER(1);
BEGIN
    SELECT COUNT(*) INTO v_result FROM Licenses WHERE LicenseID = p_licenseid AND ExpirationDate >= SYSDATE;
    IF v_result > 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/

CREATE OR REPLACE FUNCTION AvgLicenseCount(p_softwareid NUMBER)
RETURN NUMBER
IS
    v_avg NUMBER;
BEGIN
    SELECT NVL(AVG(LicenseCount),0) INTO v_avg FROM Licenses WHERE SoftwareID = p_softwareid;
    RETURN v_avg;
END;
/






CREATE OR REPLACE PROCEDURE GetLicensesBySoftware (
    p_SoftwareName NVARCHAR2
)
IS
BEGIN
    FOR rec IN (SELECT * FROM LicenseInfo WHERE SoftwareName = p_SoftwareName)
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            rec.SoftwareName || ' | ' ||
            rec.RoomName || ' | ' ||
            rec.ExpirationDate);
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE ExtendLicense (
    p_LicenseID NUMBER,
    p_Days NUMBER
)
IS
BEGIN
    UPDATE Licenses SET ExpirationDate = ExpirationDate + p_Days WHERE LicenseID = p_LicenseID;
END;
/

CREATE OR REPLACE PROCEDURE GetExpiredLicenses
IS
BEGIN
    FOR rec IN (SELECT * FROM LicenseInfo WHERE ExpirationDate < SYSDATE)
    LOOP
        DBMS_OUTPUT.PUT_LINE(rec.SoftwareName || ' expired in ' || rec.RoomName);
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE RoomLicensesCount AS
BEGIN
    FOR rec IN (
        SELECT 
            r.RoomName,
            NVL(SUM(l.LicenseCount), 0) AS TotalLicenses
        FROM Rooms r
        LEFT JOIN Licenses l ON r.RoomID = l.RoomID
        GROUP BY r.RoomName
        ORDER BY TotalLicenses DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(rec.RoomName || ' - ' || rec.TotalLicenses);
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE RoomLicenseReport (
    p_RoomID NUMBER
)
IS
BEGIN
    FOR rec IN (
        SELECT r.RoomName, s.SoftwareName, l.LicenseCount, l.Price, l.ExpirationDate FROM Licenses l
        JOIN Software s ON l.SoftwareID = s.SoftwareID
        JOIN Rooms r ON l.RoomID = r.RoomID WHERE r.RoomID = p_RoomID
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            rec.RoomName || ' | ' ||
            rec.SoftwareName || ' | ' ||
            rec.LicenseCount
        );
    END LOOP;
END;
/

