alter session set container = XEPDB1;
drop table DeviceType;
drop table Rooms;
drop table Vendors
drop table SoftwareCategories
drop table Software
drop table Licenses

CREATE TABLE DeviceType (
    DeviceTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DeviceTypeName NVARCHAR2(50) UNIQUE
);

CREATE TABLE Rooms (
    RoomID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoomName NVARCHAR2(50) UNIQUE,
    DeviceTypeID NUMBER NOT NULL,
    CONSTRAINT FK_Rooms_DeviceType FOREIGN KEY (DeviceTypeID)
        REFERENCES DeviceType(DeviceTypeID)
);

CREATE TABLE Vendors (
    VendorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VendorName NVARCHAR2(150) UNIQUE NOT NULL,
    Email NVARCHAR2(150) UNIQUE,
    Password NVARCHAR2(255) NOT NULL
);

CREATE TABLE SoftwareCategories (
    CategoryId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryName NVARCHAR2(100) NOT NULL,
    Hierarchy VARCHAR2(100) NOT NULL
);

CREATE TABLE Software (
    SoftwareID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SoftwareName NVARCHAR2(150) NOT NULL,
    VendorID NUMBER NOT NULL,
    CategoryID NUMBER NOT NULL,
    CONSTRAINT FK_Software_Vendor FOREIGN KEY (VendorID)
        REFERENCES Vendors(VendorID),
    CONSTRAINT FK_Software_Category FOREIGN KEY (CategoryID)
        REFERENCES SoftwareCategories(CategoryID)
);

CREATE TABLE Licenses (
    LicenseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SoftwareID NUMBER NOT NULL,
    RoomID NUMBER NOT NULL,
    PurchaseDate DATE NOT NULL,
    ExpirationDate DATE NOT NULL,
    Price NUMBER(10,2) CHECK (Price >= 0),
    LicenseCount NUMBER CHECK (LicenseCount > 0),
    CONSTRAINT FK_Licenses_Software FOREIGN KEY (SoftwareID)
        REFERENCES Software(SoftwareID),
    CONSTRAINT FK_Licenses_Room FOREIGN KEY (RoomID)
        REFERENCES Rooms(RoomID)
);


INSERT INTO DeviceType (DeviceTypeName) VALUES ('PC');
INSERT INTO DeviceType (DeviceTypeName) VALUES ('Laptop');
INSERT INTO DeviceType (DeviceTypeName) VALUES ('Server');
INSERT INTO DeviceType (DeviceTypeName) VALUES ('Tablet');

INSERT INTO Rooms (RoomName, DeviceTypeID) VALUES ('Room 101', 1);
INSERT INTO Rooms (RoomName, DeviceTypeID) VALUES ('Room 102', 2);
INSERT INTO Rooms (RoomName, DeviceTypeID) VALUES ('Room 201', 3);
INSERT INTO Rooms (RoomName, DeviceTypeID) VALUES ('Room 202', 1);
INSERT INTO Rooms (RoomName, DeviceTypeID) VALUES ('Room 301', 4);

INSERT INTO Vendors VALUES (DEFAULT, 'Microsoft', 'ms@mail.com', '123');
INSERT INTO Vendors VALUES (DEFAULT, 'Adobe', 'adobe@mail.com', '123');
INSERT INTO Vendors VALUES (DEFAULT, 'Oracle', 'oracle@mail.com', '123');
INSERT INTO Vendors VALUES (DEFAULT, 'JetBrains', 'jb@mail.com', '123');

INSERT INTO SoftwareCategories (CategoryName, Hierarchy) VALUES ('Operating Systems', '/');
INSERT INTO SoftwareCategories (CategoryName, Hierarchy) VALUES ('Office Software', '/');
INSERT INTO SoftwareCategories (CategoryName, Hierarchy) VALUES ('Development Tools', '/');
INSERT INTO SoftwareCategories (CategoryName, Hierarchy) VALUES ('Design Software', '/');

INSERT INTO Software (SoftwareName, VendorID, CategoryID) VALUES ('Windows 11', 1, 1);
INSERT INTO Software (SoftwareName, VendorID, CategoryID) VALUES ('MS Office', 1, 2);
INSERT INTO Software (SoftwareName, VendorID, CategoryID) VALUES ('Photoshop', 2, 4);
INSERT INTO Software (SoftwareName, VendorID, CategoryID) VALUES ('IntelliJ IDEA', 4, 3);
INSERT INTO Software (SoftwareName, VendorID, CategoryID) VALUES ('Oracle DB', 3, 3);


BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO Licenses 
        (SoftwareID, RoomID, PurchaseDate, ExpirationDate, Price, LicenseCount)
        VALUES (
            TRUNC(DBMS_RANDOM.VALUE(1, 6)), -- 1-5
            TRUNC(DBMS_RANDOM.VALUE(1, 6)), -- 1-5
            DATE '2025-01-01' + TRUNC(DBMS_RANDOM.VALUE(0, 365)),
            DATE '2026-01-01' + TRUNC(DBMS_RANDOM.VALUE(0, 365)),
            TRUNC(DBMS_RANDOM.VALUE(50, 300)),
            TRUNC(DBMS_RANDOM.VALUE(1, 21))
        );
    END LOOP;
END;
/

select * from licenses


